environment_variables: {CUDA_VISIBLE_DEVICES: "0,1,2,3"}
external_package_dirs: []
model_metadata:
  example_model_input: {"prompt": "How long would it take to reach the sun?"}
model_name: Qwen1.5-vllm-streaming
python_version: py310
requirements:
- torch==2.1.2
- transformers==4.37.0
- vllm
- asyncio==3.4.3
- ray
resources:
  accelerator: A100
  cpu: '40'
  memory: 100Gi
  use_gpu: true
secrets: {}
system_packages: []
